### PR TITLE
External image plugin calls GC

### PR DESCRIPTION
**Pull request by albertoleal**
Call external image plugin GC command.

[#133838859]

Signed-off-by: Claudia Beresford <cberesford@pivotal.io>
Signed-off-by: I am Groot

### CODE REVIEW

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#133855661](https://www.pivotaltracker.com/story/show/133855661) External image plugin calls GC


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by glestaris** [comment]
Schedule this please @julz. It's blocking #59 and they are both holding us from having GREEN GATS🎉

 Tiago, George and Groot

**Comment by glestaris** [comment]
a4dd81d850d4204cf641ebd8df1ab0c3

**Comment by tscolari** [comment]
This now also have changes for: https://www.pivotaltracker.com/story/show/134066035

**Pull request merged**
